### ISSUE TITLE
HUD functions EPIC

### ISSUE THREAD

**Issue by Gr33ndev** [Gamify-IT/issues#109]
- [x] Gamify-IT/issues#101
- [x] Gamify-IT/issues#102
- [x] Gamify-IT/issues#147
- [x] Gamify-IT/issues#108
- [x] Gamify-IT/issues#159
- [x] Gamify-IT/issues#113
- [x] Gamify-IT/issues#101
