### ISSUE TITLE
Organize Code Review for Clients

### ISSUE THREAD

**Issue by thechinese** [Gamify-IT/issues#123]
The clients expressed the explicit wish to perform a code review on a code snippet of our choice.

Code snippets:
- Bugfinder (Vue + TS)
- Moorhuhn Backend (Java + Spring)
- Moorhuhn (Unity)
~~- Overworld (Unity)~~ Cancelled as we couldn't clean it up in time
- Overwold Backend (Java + Spring)

1 person per service, review each other

## DoD

- [x] Multiple (flattering) code snippet has been chosen 
- [x] Details about all code snippet have been written down (what (not) to look at, test cases for that snippet, ...)
- [x] The clients get access to both the snippet and the documentation detailed in the step above

### Completed Cleanups

- [x] Bugfinder (Vue + TS)
- [x] Moorhuhn Backend (Java + Spring)
- [x] Moorhuhn (Unity)
- [x] Overworld (Unity)
- [x] Overwold Backend (Java + Spring)
