### ISSUE TITLE
Overworld Epic

### ISSUE THREAD

**Issue by thechinese** [Gamify-IT/issues#13]
- [x] Test changeability of tiles (to sand/snow region). #14 

- [x]     Create design for Overworld -> get approval from Uwe TODO: Link Issue  docs#24

- [x]     Level 1/2 + complete 1 dungeon (+ more if you manage more)

- [x]     Create meta model for Overworld (Class Diagram like (Overworld -> Area (=level) -> Dungeon (=level)) -> get approval from Uwe

- [ ] Sandro's Requirement: The main character should be a trash panda and the setting should be in the medivial ages
