### ISSUE TITLE
Overworld Backend: Implement needed routes that gives informations about worlds, dungeons, tasks

### ISSUE THREAD

**Issue by maexled** [Gamify-IT/issues#164]
## Requirements

Gamify-IT/issues#163

## Current Behavior

In issue Gamify-IT/issues#163 the paths were created but without logic. 

## Expected Behavior

The logic for the created paths was implemented.

### Lectures

- [x] lectures can be created
- [x] with creating a lecture the worlds will be created and linked to the lecture
- [x] lectures can be listed
- [x] a specific lecture can be shown
- [x] lectures can be updated
- [x] lectures can be deleted

### Worlds

- [x] worlds of a lecture can be listed (with informations of name, topic name, active, linked dungeons)
- [x] world topic name can be updated
- [x] world active status can be updated
- [x] a specific world of a lecture can be shown

### Dungeons
- [x] dungeons of a world can be listed
- [x] dungeon topic name can be updated
- [x] dungeon active status can be updated
- [x] a specific dungeon of a world can be shown

### Tasks
- [x] tasks of a world/dungeon can be listed
- [x] tasks of a world/dungeon can be updated (change game, change configuartionId)
- [x] a specific task of a world/dungeon can be shown
