### ISSUE TITLE
create Docker Compose files

### ISSUE THREAD

**Issue by madebyTimo** [Gamify-IT/issues#171]
## Description

All services need a construct of other services to be testet. Setting this up is very time intensive. 

The task is to create docker compose files to setup all required services.

## DoD
- [x] every service has a docker compose file to setup the environment with the service running on the pc
- [x] every service has a docker compose file to setup the environment with the service running on a locally builded docker container

**Comment by robojones** [comment]
## Todo

- [x] Moorhuhn
- [ ] Login
- [ ] Overworld
- [ ] Lecturer interface
- [ ] Bugfinder
- [ ] Crosswordpuzzle
- [ ] RegEx game
- [ ] git card game

**Comment by robojones** [comment]
## Conventions for our docker-compose files
- docker compose files:
  - `docker-compose.yaml`
  - `docker-compose-dev.yaml`
  - `docker-compose-dev-e2e.yaml`
- nginx config files
  - for the docker image: `.nginx/webgl.conf` (Unity) and `.nginx/nginx.conf` (Vue)
  - for docker-compose: `.nginx/compose/nginx.conf`
  - for docker-compose-dev: `.nginx/compose/nginx-dev.conf`
  - for docker-compose-dev-e2e: `.nginx/compose/nginx-dev-e2e.conf`
- Port assignments
  - frontend development server: `8000`
  - backend development server: `8080`
  - docker images: `80`
  - reverse proxy: `80`
