### ISSUE TITLE
Lecturer interface: Allow to modify lectures

### ISSUE THREAD

**Issue by madebyTimo** [Gamify-IT/issues#184]
## Description

Courses and their areas and minigames are configureable.

minigames means in this context the already implemented minigames (moorhuhn and crosswordpuzzle)

### Subtask added during implementation

- [x] courses get an `active` and `semester` attribute
- [x] This change is also reflected in the database model

## DoD
- [x] there exists a selection of the course to edit
- [x] courses can be created
- [x] configuration of minigames can be edited 
- [x] configuration of world can 
- [x] configuration of dungeons can be edited
- [x] configuration of npcs can be edited
