### ISSUE TITLE
World 1 EPIC

### ISSUE THREAD

**Issue by delvh** [Gamify-IT/issues#226]
- [x] copy dungeon 1 twenty times
- [x] Gamify-IT/issues#218
- [x] Gamify-IT/issues#220
- [x] Gamify-IT/issues#225
- [x] Gamify-IT/issues#221
- [x] Note hangs at each dungeon/world entrance
