### ISSUE TITLE
Overworld: Achievements

### ISSUE THREAD

**Issue by WuestFlorian** [Gamify-IT/issues#400]
## Current Behavior
There are no achievements handled by the overworld.

## Expected Behavior
There should be achievements for different things in the overworld.

## DoD
- [x] Achievement for exploring the world
- [ ] Test plan
- [x] Achievement for talking to npcs
- [ ] Test plan
- [ ] Achievement for reading books
- [ ] Test plan
- [ ] Achievement for playing minigames
- [ ] Test plan
- [ ] Achievement for activating teleporters
- [ ] Test plan
- [ ] Achievement for teleportations
- [ ] Test plan
