### ISSUE TITLE
Fix SonarQube

### ISSUE THREAD

**Issue by Gr33ndev** [Gamify-IT/issues#58]
## Current Behavior
SonarQube can not be reached from within our GitHub Action.

## Expected Behavior
GitHub Action reports to SonarQube

## ToDo
- [ ] Find out why the connection fails

## DoD
- [x] Reports are displayed in SonarQube
- [x] Error is fixed

**Comment by Gr33ndev** [comment]
Tried to reinstall Sonar, protocol is in this PR: https://github.com/Gamify-IT/docs/pull/60

**Comment by Gr33ndev** [comment]
Tried to reinstall Sonar, protocol is in this PR: https://github.com/Gamify-IT/docs/pull/60
