### ISSUE TITLE
Login: Set login token as cookie

### ISSUE THREAD

**Issue by robojones** [Gamify-IT/issues#59]
## Current Behavior
After the user logs in, the [login backend](https://github.com/Gamify-IT/login-backend) returns a token. The token can be used to identify the user in every request to any backend service. Currently, the token is only returned by the request. We should additionally set it as a cookie, so it is automatically sent to every backend.

## Expected Behavior
The token is set as a cookie called: `token`.

## DoD
- [x] The cookie can be seen in the "Network" tab of the browser debug menu, when the user is logged in
- [x] New environment variables are documented in Readme.md
- [x] The name and format of the cookie is documented in [Gamify-IT/docs](https://github.com/Gamify-IT/docs)

**Comment by robojones** [comment]
## Todo
- [ ] update dev manual
