### ISSUE TITLE
Enhance Bugfinder

### ISSUE THREAD

**Issue by madebyTimo** [Gamify-IT/issues#61]
## Description

The prototype of the bugfinder is extended by some features

## DoD
- [x] type-selection: the error-type of the bug can be selected Gamify-IT/issues#75
- [x] missing-bug: missing (key-)words can be marked as bug (for example final) Gamify-IT/issues#76
- [x] solving: bugs can be fixed in a text field Gamify-IT/issues#75
- [x] type-selection and solving can by marked optional for each code-snipped to serve different difficulty levels 
- [x] code-declaration is outside of code and easily adaptable by a backend (for example in a JSON file) Gamify-IT/issues#77
- [x] multiple bugs Gamify-IT/issues#78

**Comment by IlijazM** [comment]
it's not really a bug when a final is missing. i don't care what they think

**Comment by delvh** [comment]
Unfortunately, your opinion on that doesn't matter here.
Our client is the ISTE, and for them, a missing `final` is a bug.
