### ISSUE TITLE
Integrate minigames into Overworld

### ISSUE THREAD

**Issue by delvh** [Gamify-IT/issues#73]
### Depends on 
Gamify-IT/issues#55 and  Gamify-IT/issues#70

## Description

Minigames are integrated into the overworld and can be started according to component and sequence diagram.

## DoD
- [x] implementation fits component diagram
- [x] implementation fits sequence diagram
- [x] minigames can be played
- [x] all relevant information is communicated to the minigame
- [ ] all relevant information is communicated back from the minigames to the overworld

**Comment by delvh** [comment]
Last point has been extracted into its own issue: #224.
